engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - XXX
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"

exclude_paths:
- ez_setup.py
- versioneer.py
- gwpy/_version.py
- gwpy/tests/*
- gwpy/tests/data/*
- docs/*
- examples/*
