engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - XXX
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"

exclude_paths:
- ez_setup.py
- versioneer.py
- docs/*
- examples/*
- gwpy/_version.py
- gwpy/tests/*
- gwpy/tests/data/*
- gwpy/table/rate.py
- gwpy/table/rec.py
- gwpy/table/utils.py
- gwpy/table/io/ascii.py
