version: "2"

checks:
  argument-count:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 500

plugins:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - XXX
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"

ratings:
  paths:
  - "**.py"

exclude_paths:
- "versioneer.py"
- "docs/*"
- "examples/*"
- "gwpy/_version.py"
- "**/tests/"
- "gwpy/utils/sphinx/epydoc.py"
- "gwpy/plotter/"
