# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "mambaforge-latest"
  jobs:
    install:
      - pip install . --group dev
    post_install:
      # show what is installed in the build environment
      - conda list

conda:
  environment: docs/environment.yaml

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
