# -----------------------
#
# Run a full build-and-test from the git repo
# using a combination of conda and pip to install
# all optional dependencies.
#
# This is the 'full' test suite.
#
# -----------------------

name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  conda:
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS
          - Ubuntu
          - Windows
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    runs-on: ${{ matrix.os }}-latest

    # this is needed for conda environments to activate automatically
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Get source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache conda packages
      uses: actions/cache@v2
      env:
        # increment to reset cache
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}
        restore-keys: ${{ runner.os }}-conda-${{ matrix.python-version }}-

    - name: Cache apt (Linux)
      if: matrix.os == 'Ubuntu'
      uses: actions/cache@v2
      env:
        # increment to reset cache
        CACHE_NUMBER: 0
      with:
        path: ~/apt-cache
        key: ${{ matrix.os }}-apt-${{ env.CACHE_NUMBER }}
        restore-keys: ${{ matrix.os }}-apt-

    - name: Configure apt (Linux)
      if: matrix.os == 'Ubuntu'
      run: |
        APT_CACHE_DIR=$(readlink -f ~/apt-cache)
        mkdir -pv "${APT_CACHE_DIR}/archive/partial"
        echo "Dir::Cache \"${APT_CACHE_DIR}\";" | sudo tee /etc/apt/apt.conf.d/99cache.conf

    - name: Configure conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        channels: conda-forge
        python-version: ${{ matrix.python-version }}
        # this is needed for caching to work properly:
        use-only-tar-bz2: true

    - name: Conda info
      run: conda info --all

    - name: Install dependencies
      run: |
        # parse requirements files to install as much as possible with conda
        python ./ci/parse-conda-requirements.py \
            requirements-dev.txt \
            requirements-conda.txt \
            -o environment.txt \
            -p ${{ matrix.python-version }}
        echo "-----------------"
        cat environment.txt
        echo "-----------------"
        conda install --quiet --yes --name test --file environment.txt
        # install anything we missed with conda using regular pip
        python -m pip install -r requirements-dev.txt

    - name: Install extra dependencies (Linux)
      if: matrix.os == 'Ubuntu'
      run: |
        # update repos
        sudo DEBIAN_FRONTEND=noninteractive apt-get -y -q -q update
        # install apt requirements
        xargs -a <(awk '! /^ *(#|$)/' requirements-apt.txt) -r -- \
            sudo DEBIAN_FRONTEND=noninteractive apt-get -y -q install

    - name: Install GWpy
      run: python -m pip install . --no-build-isolation -vv

    - name: Package list
      run: conda list --name test

    - name: Run test suite
      run: python -m pytest -ra --color yes --cov gwpy --pyargs gwpy --cov-report=xml --junitxml=pytest.xml

    - name: Coverage report
      run: python -m coverage report --show-missing

    - name: Publish coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        files: coverage.xml
        flags: ${{ runner.os }},python${{ matrix.python-version }}

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: pytest-conda-${{ matrix.os }}-${{ matrix.python-version }}
        path: pytest.xml
